server:
  netty:
    connection-timeout: 5000
    idle-timeout: 6000
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
  error:
    include-stacktrace: always
  port: ${ENV_SERVER_PORT:8003}

# cloud configuration
spring:
  application:
    name: api-microservices-authentication
    version: v1
  webflux:
    base-path: /api-microservices-authentication/v1
  main:
    banner-mode: log
    lazy-initialization: false
    allow-circular-references: false
  mvc:
    converters:
      preferred-json-mapper: jsonb
  devtools:
    restart:
      enabled: true
    add-properties: false
  banner:
    location: classpath:banner.txt
  cache:
    type:
    redis:
      time-to-live: 86400000
  data:
    redis:
      host: localhost
      port: 6379