server:
  netty:
    connection-timeout: 5000
    idle-timeout: 6000
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
  error:
    include-stacktrace: always
  port: ${ENV_SERVER_PORT:8003}