
@Library('bacsystem-shared-lib') _

def params = [
                        process   : "Gitflow",
                        dsl     : this,
                        wout    : true,
                        smc     : true,
                        opt     : false
                    ]
echo "[INFO] Init process Jenkins file with ${params}"
process(params)