
@Library('bacsystem-shared-lib') _

def params = [
                        value   : "v1",
                        instance: this,
                        wout    : true,
                        smc     : true,
                        opt     : false
                    ]

process(params)