#server configuration:
server:
  netty:
    connection-timeout: 5000
    idle-timeout: 6000
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
  error:
    include-stacktrace: always
  port: ${ENV_SERVER_PORT:8761}

#spring configuration:
spring:
  application:
    name: api-microservices-eureka
    version: v1
  webflux:
    base-path: /eureka
  messages:
    encoding: UTF-8
  main:
    banner-mode: log
    lazy-initialization: false
    allow-circular-references: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  datacenter: bacsystem
  environment: test
    # dashboard:
    # enabled: true
  # path: /dashboard