server:
  netty:
    connection-timeout: 5000
    idle-timeout: 6000
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
  error:
    include-stacktrace: always
  port: ${ENV_SERVER_PORT:8888}

# cloud configuration
spring:
  application:
    name: api-microservices-gateway
    version: v1
  webflux:
    base-path: /api-microservices-gateway/v1
  main:
    banner-mode: log
    lazy-initialization: false
    allow-circular-references: false
  mvc:
    converters:
      preferred-json-mapper: jsonb
  devtools:
    restart:
      enabled: true
    add-properties: false
  banner:
    location: classpath:banner.txt
  cache:
    type:
    redis:
      time-to-live: 86400000
  #  data:
  #    redis:
  #      host: localhost
  #      port: 0
  cloud:
    vault:
      authentication: token
      token: 00000000-0000-0000-0000-000000000000
      scheme: http
      port: 8200
      host: localhost
# vault server --dev --dev-root-token-id="00000000-0000-0000-0000-000000000000"
# vault kv put secret/api-microservices-authentication @api-microservices-authentication.json
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}