services:

  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./tmp/jenkins:/var/jenkins_home  # persistence volume
    networks:
      - bacsystem

networks:
  bacsystem:
    name: bacsystem-net
    driver: bridge