CREATE TABLE PATIENT
(
    ID numeric PRIMARY KEY
);
--Este patrón se conoce como “just-in-time provisioning”.

CREATE TABLE DATA_USER
(
    ID           NUMERIC PRIMARY KEY,
    UUID         UUID NOT NULL UNIQUE,
    KEYCLOAK_ID  UUID NOT NULL UNIQUE,
    EMAIL        VARCHAR(100) UNIQUE,
    NAME         VARCHAR(100),
    LASTNAME     VARCHAR(100),
    PHONE        VARCHAR(30),
    ROLE         VARCHAR(30),
    STATUS       INT  NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DATA_PARAMETRIC
(
    ID           NUMERIC PRIMARY KEY NOT NULL,
    CODE_TABLE   INT                 NOT NULL,
    CORRELATIVE  INT                 NOT NULL,
    DESCRIPTION  VARCHAR(1000),
    ABBREVIATION VARCHAR(10),
    ORDERED      INT       DEFAULT 0,
    STATUS       BOOLEAN   DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

